spring:
  datasource:
    url: jdbc:mysql://app-works-demo-mysql:3306/appworks?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: app-works-demo-redis-master
      port: 6379
      timeout: 10000
      lettuce:
        pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
