server:
  port: 8080
spring:
  application:
    name: app-works-demo
  datasource:
    url: jdbc:mysql://app-works-demo-mysql:3306/appworks?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: appworks
    password: appworks
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: app-works-demo-redis-master
      port: 6379
      timeout: 10000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  observations:
    key-values:
      application: ${spring.application.name}
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ "prometheus","health" ]